#pragma once

template <class T>
class CProxy_IGetCardInfoEvents : public IConnectionPointImpl<T, &__uuidof( _IGetCardInfoEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
